// Last phase, falling spears (Raging Storm): is there a rule for the two NON-fixated targets of a set? (see raging_storm_targets.js for the sets)
// For every set with exactly two non-fixated targets, the candidates (living, non-fixated players at the moment the set starts) are ranked by a
// feature, and the script counts how often the two targets are the 2 lowest or the 2 highest ranked. A real rule would put them there
// (near 100 %); chance is 2 / number of candidates.
// Features: distance from Vloxx, from the arena centre, from the fixated player, from each Aspect; health; order in the squad; instance id;
// damage done to Vloxx in the last 12 / 30 s; toughness; time since last targeted; downed. Also the distance between the two targets.
// Writes data/raging_storm_target_rule.json.
const fs = require('fs'), path = require('path'); const { parseEvtc } = require('./evtc'); const dir = path.join(__dirname, '..', 'logs', 'raw') + path.sep; const pb = Buffer.alloc(8); const C = [12221.6, 15327.4];
const feats = {}; const add = (name, rankLow, n) => { const o = (feats[name] = feats[name] || { top2: 0, bot2: 0, n: 0, chance: 0, ranks: {} }); o.n++; if (rankLow <= 2) o.top2++; if (rankLow > n - 2) o.bot2++; o.chance += 2 / n; o.ranks[rankLow] = (o.ranks[rankLow] || 0) + 1; };
let sets = 0; const pairDist = [], pairDistRand = []; const dump = [];
for (const f of fs.readdirSync(dir).sort()) { const { agents, ev } = parseEvtc(dir + f); const boss = [...agents.values()].find(a => a.species === 28106); if (!boss) continue; const lc = ev.find(e => e.sc === 67 && e.src === boss.addr && e.skill === 81071); if (!lc) continue;
  const isP = a => (agents.get(a) || {}).isPlayer; const P = [...agents.values()].filter(a => a.isPlayer); const order = new Map(P.map((a, i) => [a.addr, i])); const instOf = new Map(); for (const e of ev) if (e.srcInst && isP(e.src) && !instOf.has(e.src)) instOf.set(e.src, e.srcInst);
  const gid = new Map(); for (const e of ev) if (e.sc === 46) { const b = Buffer.alloc(16); b.writeBigUInt64LE(e.src, 0); b.writeBigUInt64LE(e.dst, 8); gid.set(e.skill, b.toString('hex').toUpperCase().slice(0, 8)); }
  const life = new Map(), pos = new Map(), hp = new Map(); for (const e of ev) { if ([3, 4, 5, 7].includes(e.sc)) (life.get(e.src) || life.set(e.src, []).get(e.src)).push([e.t, e.sc]); if (e.sc === 19) { pb.writeBigUInt64LE(e.dst); (pos.get(e.src) || pos.set(e.src, []).get(e.src)).push([e.t, pb.readFloatLE(0), pb.readFloatLE(4)]); } if (e.sc === 8) (hp.get(e.src) || hp.set(e.src, []).get(e.src)).push([e.t, Number(e.dst) / 100]); }
  const st = (a, t) => { let s = 3; for (const x of life.get(a) || []) { if (x[0] > t) break; if ([3, 4, 5].includes(x[1])) s = x[1]; } return s; }; const stepv = (m, a, t, d) => { let r = d; for (const x of m.get(a) || []) { if (x[0] > t) break; r = x; } return r; };
  const lerp = (a, t) => { const p = pos.get(a) || []; let lo = null, hi = null; for (const x of p) { if (x[0] <= t) lo = x; else { hi = x; break; } } if (!lo) return null; if (!hi) return lo.slice(1); const k = (t - lo[0]) / (hi[0] - lo[0]); return [lo[1] + k * (hi[1] - lo[1]), lo[2] + k * (hi[2] - lo[2])]; };
  const fxb = ev.filter(e => e.skill === 34508 && ((e.sc === 69 && isP(e.dst)) || ((e.sc === 71 || e.sc === 72) && isP(e.src)))).sort((a, b) => a.t - b.t); const holderAt = t => { let h = null, end = 0; for (const e of fxb) { if (e.t > t) break; if (e.sc === 69) { h = e.dst; end = e.t + e.value; } else if (e.src === h) h = null; } return h != null && end > t ? h : null; };
  const firstSeen = new Map(); for (const e of ev) if (e.src && !firstSeen.has(e.src)) firstSeen.set(e.src, e.t);
  const aspPos = (sp, t) => { const a = [...agents.values()].find(x => x.species === sp && (firstSeen.get(x.addr) ?? Infinity) <= t && !(life.get(x.addr) || []).some(([tt, sc]) => (sc === 4 || sc === 7) && tt <= t)); if (!a) return null; const r = stepv(pos, a.addr, t, null); return r ? [r[1], r[2]] : null; };
  const dmgTo = new Map(); for (const e of ev) if (e.sc === 0 && e.dst === boss.addr && isP(e.src) && e.t >= lc.t - 30000) (dmgTo.get(e.src) || dmgTo.set(e.src, []).get(e.src)).push([e.t, e.buff ? e.buffDmg : e.value]);
  const fx = ev.filter(e => e.sc === 60 && e.src === boss.addr && gid.get(e.skill) === 'D1132020' && e.t >= lc.t).map(e => { pb.writeBigUInt64LE(e.dst); return { t: e.t, x: pb.readInt16LE(0) * 10, y: pb.readInt16LE(2) * 10 }; });
  const W = new Map(); for (const e of fx) { const slot = Math.round((e.t - lc.t) / 3000) * 3; const w = W.get(slot) || W.set(slot, { t: e.t, pts: [] }).get(slot); w.pts.push(e); }
  const lastT = new Map();
  for (let s = 15; W.has(s + 6); s += 12) { const a = W.get(s + 6); const t0 = lc.t + s * 1000; // decision time = set start
    const liveA = P.filter(p => st(p.addr, a.t) !== 4).map(p => ({ a: p.addr, q: lerp(p.addr, a.t), ag: p })).filter(o => o.q); const tg = []; let bad = false; for (const p of a.pts) { let best = null, bd = 1e9; liveA.forEach(o => { const d = Math.hypot(o.q[0] - p.x, o.q[1] - p.y); if (d < bd) { bd = d; best = o; } }); if (best && bd < 80) tg.push(best.a); else bad = true; } if (bad) continue;
    const h = holderAt(t0) ?? holderAt(a.t); const set = new Set(tg); const nf = [...set].filter(v => v !== h); if (nf.length !== 2) continue; sets++;
    const bpR = stepv(pos, boss.addr, t0, null); const bp = bpR ? [bpR[1], bpR[2]] : C; const hq = h != null ? lerp(h, t0) : null;
    const cand = P.filter(p => st(p.addr, t0) !== 4 && p.addr !== h).map(p => ({ a: p.addr, q: lerp(p.addr, t0), ag: p })).filter(o => o.q); const n = cand.length; if (nf.some(v => !cand.some(o => o.a === v))) continue;
    const F = { 'distance from Vloxx (1 = closest)': o => Math.hypot(o.q[0] - bp[0], o.q[1] - bp[1]), 'distance from arena centre': o => Math.hypot(o.q[0] - C[0], o.q[1] - C[1]), 'health % (1 = lowest)': o => stepv(hp, o.a, t0, [0, 100])[1], 'squad order in the log': o => order.get(o.a), 'instance id': o => instOf.get(o.a) || 0,
      'damage to Vloxx in the last 12 s (1 = least)': o => (dmgTo.get(o.a) || []).filter(x => x[0] > t0 - 12000 && x[0] <= t0).reduce((q, x) => q + x[1], 0), 'damage to Vloxx in the last 30 s (1 = least)': o => (dmgTo.get(o.a) || []).filter(x => x[0] > t0 - 30000 && x[0] <= t0).reduce((q, x) => q + x[1], 0),
      'toughness flag (1 = lowest)': o => o.ag.toughness + order.get(o.a) / 100, 'time since last targeted (1 = most recent)': o => t0 - (lastT.get(o.a) ?? -1e9), 'downed first': o => st(o.a, t0) === 5 ? 0 : 1 + order.get(o.a) / 100 };
    if (hq) F['distance from the fixated player'] = o => Math.hypot(o.q[0] - hq[0], o.q[1] - hq[1]);
    for (const [nm, sp] of [['Staff', 28017], ['Spear', 28033], ['Sword', 28107]]) { const ap = aspPos(sp, t0); if (ap) F['distance from the ' + nm + ' Aspect'] = o => Math.hypot(o.q[0] - ap[0], o.q[1] - ap[1]); }
    for (const [name, fn] of Object.entries(F)) { const sorted = cand.slice().sort((x, y) => fn(x) - fn(y)); nf.forEach(v => add(name, sorted.findIndex(o => o.a === v) + 1, n)); }
    const A = cand.find(o => o.a === nf[0]), B = cand.find(o => o.a === nf[1]); pairDist.push(Math.hypot(A.q[0] - B.q[0], A.q[1] - B.q[1])); for (let i = 0; i < cand.length; i++) for (let j = i + 1; j < cand.length; j++) pairDistRand.push(Math.hypot(cand[i].q[0] - cand[j].q[0], cand[i].q[1] - cand[j].q[1]));
    nf.forEach(v => lastT.set(v, t0)); if (dump.length < 6) { const sorted = cand.slice().sort((x, y) => F['distance from Vloxx (1 = closest)'](x) - F['distance from Vloxx (1 = closest)'](y)); dump.push(f.slice(0, 15) + ' s' + s + ' n' + n + ' Vloxx-dist ranks of targets: ' + nf.map(v => sorted.findIndex(o => o.a === v) + 1).join(',') + ' | dists ' + sorted.map(o => Math.round(F['distance from Vloxx (1 = closest)'](o)) + (nf.includes(o.a) ? '*' : '')).join(' ')); } } }
console.log('sets with exactly 2 non-fixated targets:', sets);
fs.writeFileSync(path.join(__dirname, '..', 'data', 'raging_storm_target_rule.json'), JSON.stringify({ sets, features: Object.fromEntries(Object.entries(feats).map(([k, o]) => [k, { targetChecks: o.n, inTheTwoLowestPct: Math.round(100 * o.top2 / o.n), inTheTwoHighestPct: Math.round(100 * o.bot2 / o.n), chancePct: Math.round(100 * o.chance / o.n) }])), distanceBetweenTheTwoTargets: { median: pairDist.slice().sort((x, y) => x - y)[Math.floor(pairDist.length / 2)] | 0, anyTwoCandidatesMedian: pairDistRand.slice().sort((x, y) => x - y)[Math.floor(pairDistRand.length / 2)] | 0 } }, null, 1)); const md = a => Math.round(a.sort((x, y) => x - y)[Math.floor(a.length / 2)]);
console.log('feature'.padEnd(48) + 'targets in the 2 lowest   in the 2 highest   chance   rank histogram');
for (const [k, o] of Object.entries(feats)) console.log(k.padEnd(48) + (Math.round(100 * o.top2 / o.n) + ' %').padStart(10) + (Math.round(100 * o.bot2 / o.n) + ' %').padStart(20) + (Math.round(100 * o.chance / o.n) + ' %').padStart(13) + '   ' + Object.entries(o.ranks).map(([r, c]) => r + ':' + c).join(' '));
console.log('distance between the two targets: median', md(pairDist), '| any two candidates: median', md(pairDistRand)); console.log(dump.join('\n'));
